spring:

  # 数据库配置
  datasource:
    url: jdbc:mysql://182.254.151.43/learning
    username: learning_user
    password: Learning_user_2017
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # Redis配置
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: 182.254.151.43
    # redis端口（默认为6379）
    port: 6380
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1
  # 让控制台输出的日志有颜色
  output:
    ansi:
      enabled: detect



# 服务器配置
server:
  port: 8080

# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.maxwell.redisdemo.entity
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
    - mapper/ProductMapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# 日志配置
logging:
  level:
    org.springframework: DEBUG
    org.spring.springboot.dao: DEBUG
    org.ibatis: DEBUG
    com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    com.ibatis.common.jdbc.ScriptRunner: DEBUG
    com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    com.maxwell.redisdemo.dao: DEBUG
    com.maxwell.redisdemo: DEBUG
  file: logs/spring-boot-logging.log


debug: true

